"""empty message

Revision ID: 65cc20af95d0
Revises: 09e587bd2635
Create Date: 2025-02-07 13:24:37.022292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cc20af95d0'
down_revision = '09e587bd2635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
